rules:
  bem-depth:
    - 2
    - max-depth: 2
  class-name-format:
    -
      allow-leading-underscore: false
    -
      convention: hyphenatedbem
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 2
    -
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  nesting-depth:
    - 2
    -
      max-depth: 3
  no-attribute-selectors: 2
  no-ids: 0
  no-qualifying-elements: 0
  no-universal-selectors: 2
  property-sort-order:
    - 2
    -
      order: concentric
  indentation:
    - 2
    -
      size: 2
  no-empty-rulesets:
    - 2
  no-color-literals:
    - 2
  empty-line-between-blocks:
    - 2
  final-newline:
    - 2
  quotes:
    - 2
  no-vendor-prefixes:
    - 2
  trailing-semicolon:
    - 2
  empty-args:
    -2
